# Generated by Django 5.1.7 on 2025-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='gender',
        ),
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
