# Generated by Django 5.1.7 on 2025-04-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_data_age_remove_data_gender_data_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
    ]
